### ISSUE TITLE
Mutually recursive function syntax

### ISSUE THREAD

**Issue by samueleaton** [hoest/sublimetext-fsharp#13]
Doesn't support the mutually recursive function syntax as described here: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/recursive-functions-the-rec-keyword

```
// Mutually recursive functions:
let rec function1-nameparameter-list =
    function1-body

and function2-nameparameter-list =
    function2-body
...
```
Example:
```fsharp
let rec Even x = 
    if x = 0 then true 
    else Odd (x-1) 
and Odd x = 
    if x = 0 then false 
    else Even (x-1)
```

## Screenshots:
`Odd` is not recognized as a function:
![Screen Shot 2022-06-13 at 4 07 13 PM](https://user-images.githubusercontent.com/9119269/173461931-90bb895b-b447-417c-bde5-123a9b1ec981.png)
![Screen Shot 2022-06-13 at 4 07 54 PM](https://user-images.githubusercontent.com/9119269/173462014-75234b73-95e9-4c4c-95fa-2e2c7cd4f0d9.png)
![Screen Shot 2022-06-13 at 4 08 03 PM](https://user-images.githubusercontent.com/9119269/173462023-74aabdea-3fe7-434a-a997-a66193b9cdd1.png)

**Comment by samueleaton** [comment]
This simple addition below fixes it. I copied the `.sublime-syntax` file locally and it worked. I saw that the [official Sublime OCaml package](https://github.com/sublimehq/Packages/blob/master/OCaml/OCaml.sublime-syntax#L43) just has `let|and` in the syntax def so I copied it.

```yaml
...
definition:
    # "and" added between "|let|" and "|member val|"
    - match: '\b(let mutable|static let mutable|static let|let inline|let|and|member val|static member inline|static member|default|member|override|let!)(\s+rec|mutable)?(\s+\[\<.*\>\])?\s*(private|internal|public)?\s+(\[[^-=]*\]|[_[:alpha:]]([_[:alpha:]0-9\._]+)*|``[_[:alpha:]]([_[:alpha:]0-9\._`\s]+|(?<=,)\s)*)?'
      captures:
        1: keyword.fsharp
        2: keyword.fsharp
        3: support.function.attribute.fsharp
        4: storage.modifier.fsharp
        5: variable.fsharp
      push:
        - meta_scope: binding.fsharp
        - match: \s*(with\b|=|\n+=|(?<=\=))
          captures:
            1: keyword.fsharp
          pop: true
        - include: common_binding_definition
...
```
